### ISSUE TITLE
generel information function

### ISSUE THREAD

**Issue by TobiasDemuth** [TobiasDemuth/Assistant-Ghost#6]
### basic unstructions:

![image](https://github.com/TobiasDemuth/Assistent-Ghost/assets/150724275/be4377ac-11b4-4a14-b8db-e336036d665c)

so just  use the given library and implement it in the code

1. Input keywords at the beginning of the file
2. Def a function that takes the user_input and returns the general information 
3. Use the user input adjust it if needed and use your wikipedia function with the input
4. response = your_function(user_input)

See the other functions and user_input processing as an example

# File : [speech_assisten.py](https://github.com/TobiasDemuth/Assistent-Ghost/blob/main/speech_assistent.py)

**Comment by Abhi13e** [comment]
Hey, can you assigned this issue to me i will look it into

**Comment by Abhi13e** [comment]
Hey can you elaborate more this issue and it's good if you provide requirement.txt

**Comment by TobiasDemuth** [comment]
> Hey can you elaborate more this issue and it's good if you provide requirement.txt @Abhi13e 

i wrote them in the Readme but thanks for the advice 
is it better now?

**Comment by TobiasDemuth** [comment]
## Hey @Abhi13e 

you on this right now? if yes please answer till at latest tomorrow afternoon otherwise I'm gonna have to remove you from Assignes and will do it myself.

best regards Tobi ._.

**Comment by Abhi13e** [comment]
> ## Hey @Abhi13e
> you on this right now? if yes please answer till at latest tomorrow afternoon otherwise I'm gonna have to remove you from Assignes and will do it myself.
> 
> best regards Tobi ._.

Hey can you give me some time? currently i am not starting this

**Comment by TobiasDemuth** [comment]
@Abhi13e sure thing no worries but this feature should be ready soon 
Till when do you think you can do it?

**Comment by Abhi13e** [comment]
> @Abhi13e sure thing no worries but this feature should be ready soon Till when do you think you can do it?

Hey @TobiasDemuth I succesfully make that feature and it works also fine

**Comment by TobiasDemuth** [comment]
> Hey @TobiasDemuth I succesfully make that feature and it works also fine

@Abhi13e Really cool! if you would like to just create a pull request and i will review it and adjust it if needed.
I Appreciate your work!

**Comment by Abhi13e** [comment]
> > Hey @TobiasDemuth I succesfully make that feature and it works also fine
> 
> @Abhi13e Really cool! if you would like to just create a pull request and i will review it and adjust it if needed. I Appreciate your work!

Hey @TobiasDemuth I create pull request pls review it once and then tell if there is necessary changes.
